name: Move MP3 Files to docs/gtts

on:
  workflow_dispatch:  # Manual trigger

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Move MP3 files to docs/gtts
        run: |
          mkdir -p docs/gtts
          shopt -s nullglob
          for file in gtts/*.mp3; do
            mv "$file" docs/gtts/
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/gtts/*.mp3
          git rm -f gtts/*.mp3 || true
          git commit -m "Move mp3 files from gtts/ to docs/gtts" || echo "No changes to commit"
          git push
