name: Generate MP3 Playlist

on:
  workflow_dispatch:
  push:
    paths:
      - 'gtts/**/*.mp3'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate playlist.json
        run: |
          mkdir -p docs/assets
          echo "[" > docs/assets/playlist.json
          find gtts -name '*.mp3' | sort | sed 's/^/  "/;s/$/",/' >> docs/assets/playlist.json
          sed -i '$ s/,$//' docs/assets/playlist.json
          echo "]" >> docs/assets/playlist.json

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/assets/playlist.json
          git commit -m "Update playlist.json"
          git push
